// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d1e2ee96-ba3b-4618-b076-1793c58ad702",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XBq0KY7QO",
    "aws_user_pools_web_client_id": "12bae7824ciim29b74ear4cu7e",
    "oauth": {}
};


export default awsmobile;
